---
- hosts: localhost
  connection: local

  tasks:
    - name: debug all the ansible variables
      debug:
        msg: 
          - "{{ ansible_facts['env']['MY_GENERIC_PASSWORD'] }}"
          - "{{ ansible_facts['env']['MY_GENERIC_USERNAME'] }}"

    - name: debug what variables are available
      debug:
        msg: 
          - "my_generic_password: {{ my_generic_password }}"
          - "my_generic_username: {{ my_generic_username }}"


    #- name: debug some localhost vars
    #  debug:
    #    msg: "{{ hostvars['localhost'] }}"
        

    #    - name: set fact on the prefix stuff
    #      set_fact:  
    #        "{{ my_passwd | prefix(my_prefix) }}": "{{ my_passwd }}"
    #        "{{ my_user | prefix(my_prefix)  }}": "{{ my_user }}"
    #
    #    - name: debug variable
    #      debug:
    #        msg: 
    #          - "{{ hostvars['localhost'] }}"
    #          #          - "{{ ansible_facts }}"

#          - "here are the values"
#          - "{{ password_prefix.values() | list }}"



#        password_prefix: "{{ passwd | prefix(prefix) }}"
#        {"{{ key }}":"{{ item.val }}"}
  
#- name: first run of this filter, how are we doing
#  debug:
#    msg: "{{ user | prefix(prefix) }}"

#- name: print the k,v of dict
#  debug:
#    msg: 
#      "{{ passwd | prefix(prefix) }}"
